# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CypherPlaygroundGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, message, key):
        import sys
        app = QtWidgets.QApplication(sys.argv)
        form = QtWidgets.QWidget()
        ui = Ui_Form()
        ui.setupUi(form)
        form.show()
        sys.exit(app.exec_())

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(565, 399)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(180, 20, 361, 151))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(20, 90, 131, 281))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(180, 190, 361, 181))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(20, 60, 62, 14))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 60, 62, 14))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "Caeser Cypher"))
        self.comboBox.setItemText(1, _translate("Form", "Vigenere Cypher"))
        self.comboBox.setItemText(2, _translate("Form", "XOR Algorithm"))
        self.plainTextEdit.setPlainText(_translate("Form", "Input message"))
        self.plainTextEdit_2.setPlainText(_translate("Form", "Input key"))
        self.plainTextEdit_3.setPlainText(_translate("Form", "Resulting text"))
        self.radioButton.setText(_translate("Form", "Ecrypt"))
        self.radioButton_2.setText(_translate("Form", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
